# -*- coding: utf-8 -*-
"""Copia de EMG1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18q_KHx3PEaEyjowmDlt1V_2XC5yXqapw

#Pulgar en reposo
"""

import numpy as np
import matplotlib.pyplot as plt

# Cargar los datos de la señal EMG desde el archivo de texto

#PULGAR
emg_data = np.loadtxt('pulgar_reposo.txt')
#emg_data = np.loadtxt('pulgar_flexion.txt')
#emg_data = np.loadtxt('pulgar_contrafuerza.txt')

#BICEPS
#emg_data = np.loadtxt('biceps_reposo.txt')
#emg_data = np.loadtxt('biceps_flexion.txt')
#emg_data = np.loadtxt('biceps_contrafuerza.txt')

#PANTORRILLA
#emg_data = np.loadtxt('pantorrilla_reposo.txt')
#emg_data = np.loadtxt('pantorrilla_flexion.txt')
#emg_data = np.loadtxt('pantorrilla_contrafuerza.txt')

# Seleccionar la última columna que contiene los valores de la señal EMG
columna_emg = emg_data[:, -1]
#Debido a que la señal muestreada por el EMG del BiTalino son del ADC de 10 bits; entonces esta data oscila
#de 0-1023. Pero considerando que el voltaje de operación es de 3.3V, se debe hacer una conversión de 0-1023 a 0-3.3V
columna_Volt = ((columna_emg-507)/1023)*3.3*1000
#Dadon que el BiTalino te brinda el total de datos y no el tiempo, podemos obtener
#la duración del muestreo gracias a la frecuencia de meustreo del BiTalino: 1000 Hz
fs = 1000
total_data = len(columna_Volt)
time_total = total_data/fs
#Teniendo la duración y la cantidad de muestreo, se realizó otra lista para el eje X
#que equivale al Tiempo, con intervalos iguales para obtener un tamaño de lista igual al del Eje Y
time_data = np.linspace(0,time_total,total_data)
#Para visulaizar solo una porción del gráfico
t_start = 8.5 # @param {type:"number"}
t_end = 9.2  # @param {type:"number"}
index_start = round(t_start*(total_data-1)/time_total)
index_end = round(t_end*(total_data-1)/time_total)
# Plotear la señal EMG en el dominio del tiempo
plt.plot(time_data,columna_Volt)
plt.xlabel('Tiempo (s)')
plt.ylabel('Voltaje (mV)')

#PULGAR
plt.title('Señal EMG del dedo Pulgar en reposo')
#plt.title('Señal EMG del dedo Pulgar en flexión')
#plt.title('Señal EMG del dedo Pulgar con contrafuerza')

#BICEPS
#plt.title('Señal EMG del Biceps en reposo')
#plt.title('Señal EMG del Biceps en flexión')
#plt.title('Señal EMG del Biceps con contrafuerza')

#PANTORILLA
#plt.title('Señal EMG de la Pierna reposo')
#plt.title('Señal EMG del Pierna en flexión')
#plt.title('Señal EMG del Pierna con contrafuerza')

plt.grid(True)
plt.show()

# Plotear la señal EMG en solo un intervalo del tiempo
plt.plot(time_data[index_start:index_end],columna_Volt[index_start:index_end])
plt.xlabel('Tiempo (s)')
plt.ylabel('Voltaje (mV)')
plt.title('Intervalo del EMG')
plt.grid(True)
plt.show()